# SOPS configuration file
keys:
  # User SSH key converted to age
  - &user_key age1mpdp73dg6ndc8vq55qmnsfzu7qz6dkaft6awg475pgr6lr7kevyqj9hlgc
  # System SSH host key converted to age
  - &system_key age10f5p9pzkm8579v8gdwgpe04uy7hj83hml9fxu93tedu9xd78fg3qmkuju7

creation_rules:
  # Default rule for all secrets using both keys
  - path_regex: .*\.yaml$
    key_groups:
      - age:
          - *user_key
          - *system_key
