# SOPS configuration file
keys:
  # User SSH key converted to age
  - &user_key age1mpdp73dg6ndc8vq55qmnsfzu7qz6dkaft6awg475pgr6lr7kevyqj9hlgc

creation_rules:
  # Default rule for all secrets using user key
  - path_regex: .*\.yaml$
    key_groups:
      - age:
          - *user_key
