# Hardware configuration for nixberry (Parallels Desktop aarch64 VM)
# Generated by nixos-generate-config after setup.sh partitioning.
# Partition layout:
#   sda1 — 256M EFI System Partition (FAT32)
#   sda2 — 8G swap
#   sda3 — btrfs (subvols: root, home, nix, workplace)

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # ── Kernel / initrd ──────────────────────────────────────────────────
  boot.initrd.availableKernelModules = [ "ehci_pci" "xhci_pci" "usbhid" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # ── Btrfs subvolume layout ───────────────────────────────────────────
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d497df0a-be76-446f-a04a-611166d738e8";
    fsType = "btrfs";
    options = [ "subvol=root" "compress=zstd" "noatime" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/d497df0a-be76-446f-a04a-611166d738e8";
    fsType = "btrfs";
    options = [ "subvol=home" "compress=zstd" "noatime" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/d497df0a-be76-446f-a04a-611166d738e8";
    fsType = "btrfs";
    options = [ "subvol=nix" "compress=zstd" "noatime" ];
  };

  fileSystems."/workplace" = {
    device = "/dev/disk/by-uuid/d497df0a-be76-446f-a04a-611166d738e8";
    fsType = "btrfs";
    options = [ "subvol=workplace" "compress=zstd" "noatime" ];
  };

  # ── ESP ──────────────────────────────────────────────────────────────
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/ED09-7DA6";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  # ── Swap ─────────────────────────────────────────────────────────────
  swapDevices = [
    { device = "/dev/disk/by-uuid/0457cac8-6d84-4fc0-ad53-b3dbf79ee20f"; }
  ];

  # ── Platform ─────────────────────────────────────────────────────────
  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";

  # ── Parallels Guest Integration ──────────────────────────────────────
  # prl-tools is unfree — handled via allowUnfree = true in mkPkgs (flake.nix)
  hardware.parallels.enable = true;
}
