# Hardware configuration for nixbox (VirtualBox/VMware x86_64 VM)
# Generated by nixos-generate-config after setup.sh partitioning.
# Partition layout:
#   sda1 — 512M EFI System Partition (FAT32)
#   sda2 — 8G swap
#   sda3 — btrfs (subvols: root, home, nix, workplace)

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # ── Kernel / initrd ──────────────────────────────────────────────────
  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "virtio_pci"
    "virtio_scsi"
    "virtio_blk"
    "sd_mod"
    "sr_mod"
    "ehci_pci"
    "ohci_pci"
    "vmw_pvscsi"    # VMware paravirtual SCSI
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # ── Btrfs subvolume layout ───────────────────────────────────────────
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a1b2c3d4-e5f6-7890-abcd-ef1234567890";
    fsType = "btrfs";
    options = [ "subvol=root" "compress=zstd" "noatime" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/a1b2c3d4-e5f6-7890-abcd-ef1234567890";
    fsType = "btrfs";
    options = [ "subvol=home" "compress=zstd" "noatime" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/a1b2c3d4-e5f6-7890-abcd-ef1234567890";
    fsType = "btrfs";
    options = [ "subvol=nix" "compress=zstd" "noatime" ];
  };

  fileSystems."/workplace" = {
    device = "/dev/disk/by-uuid/a1b2c3d4-e5f6-7890-abcd-ef1234567890";
    fsType = "btrfs";
    options = [ "subvol=workplace" "compress=zstd" "noatime" ];
  };

  # ── ESP ──────────────────────────────────────────────────────────────
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/ABCD-1234";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  # ── Swap ─────────────────────────────────────────────────────────────
  swapDevices = [
    { device = "/dev/disk/by-uuid/12345678-abcd-ef01-2345-6789abcdef01"; }
  ];

  # ── Platform ─────────────────────────────────────────────────────────
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # ── VirtualBox / VMware Guest Integration ────────────────────────────
  # VirtualBox Guest Additions
  virtualisation.virtualbox.guest.enable = lib.mkDefault true;

  # VMware Tools (enable one or the other depending on hypervisor)
  # Uncomment for VMware, comment out virtualbox above:
  # virtualisation.vmware.guest.enable = true;
}
